package views;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author Elián
 */
public class MenuUsuario extends javax.swing.JFrame {

    Date fechaActual = new Date();
    String fecha = new SimpleDateFormat("dd/MM/yyyy").format(fechaActual);
    int xMouse, yMouse;

    public MenuUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        registroReservasLabel = new javax.swing.JLabel();
        busquedaLabel = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        sistemaPanel = new javax.swing.JPanel();
        reservasLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        texto1Label = new javax.swing.JLabel();
        texto2Label = new javax.swing.JLabel();
        texto3Label = new javax.swing.JLabel();
        texto4Label = new javax.swing.JLabel();
        texto5Label = new javax.swing.JLabel();
        texto6Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 944, 609));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(12, 138, 199));
        menuPanel.setToolTipText("");

        logoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elián\\Documents\\NetBeansProjects\\HotelAlura\\src\\main\\java\\views\\imagenes\\aH-150px.png")); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        registroReservasLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registroReservasLabel.setForeground(new java.awt.Color(255, 255, 255));
        registroReservasLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        registroReservasLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elián\\Documents\\NetBeansProjects\\HotelAlura\\src\\main\\java\\views\\imagenes\\icon-reservas.png")); // NOI18N
        registroReservasLabel.setText("Registro de reservas");
        registroReservasLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registroReservasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroReservasLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registroReservasLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registroReservasLabelMouseExited(evt);
            }
        });

        busquedaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        busquedaLabel.setForeground(new java.awt.Color(255, 255, 255));
        busquedaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        busquedaLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elián\\Documents\\NetBeansProjects\\HotelAlura\\src\\main\\java\\views\\imagenes\\pessoas.png")); // NOI18N
        busquedaLabel.setText("Búsqueda");
        busquedaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busquedaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busquedaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                busquedaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                busquedaLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(logoLabel))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registroReservasLabel)
                            .addComponent(busquedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(logoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(registroReservasLabel)
                .addGap(18, 18, 18)
                .addComponent(busquedaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        jPanel2.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 240, 650));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitLabel.setBackground(new java.awt.Color(255, 255, 255));
        exitLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.setOpaque(true);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 914, Short.MAX_VALUE)
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel2.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        sistemaPanel.setBackground(new java.awt.Color(118, 187, 223));
        sistemaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservasLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        reservasLabel.setForeground(new java.awt.Color(255, 255, 255));
        reservasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservasLabel.setText("Sistema de reservas Hotel Alura");
        sistemaPanel.add(reservasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 710, -1));

        fechaLabel.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaLabel.setText("Hoy es " + fecha);
        sistemaPanel.add(fechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 710, -1));

        jPanel2.add(sistemaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 710, 130));

        texto1Label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        texto1Label.setText("Bienvenido");
        jPanel2.add(texto1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        texto2Label.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        texto2Label.setText("<html><body>Sistema de reserva de hotel. Controle y administre de forma óptima y fácil <br> el flujo de reservas y de huespédes del hotel   </body></html>");
        jPanel2.add(texto2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 570, 70));

        texto3Label.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        texto3Label.setText("<html><body>Esta herramienta le permitirá llevar un control completo y detallado de sus reservas y huéspedes, tendrá acceso a heramientas especiales para tareas específicas como lo son:</body></html>");
        jPanel2.add(texto3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 600, 90));

        texto4Label.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        texto4Label.setText("- Registro de Reservas y Huéspedes");
        jPanel2.add(texto4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, -1));

        texto5Label.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        texto5Label.setText("- Edición de Reservas y Huéspedes existentes");
        jPanel2.add(texto5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, -1));

        texto6Label.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        texto6Label.setText("- Eliminar todo tipo de registros");
        jPanel2.add(texto6Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitLabel.setBackground(Color.red);
        exitLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitLabel.setBackground(Color.white);
        exitLabel.setForeground(Color.black);
    }//GEN-LAST:event_exitLabelMouseExited

    private void registroReservasLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroReservasLabelMouseEntered
        registroReservasLabel.setFont(new java.awt.Font("Segoe UI", 1, 19));
    }//GEN-LAST:event_registroReservasLabelMouseEntered

    private void registroReservasLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroReservasLabelMouseExited
        registroReservasLabel.setFont(new java.awt.Font("Segoe UI", 1, 18));
    }//GEN-LAST:event_registroReservasLabelMouseExited

    private void busquedaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busquedaLabelMouseEntered
        busquedaLabel.setFont(new java.awt.Font("Segoe UI", 1, 19));
    }//GEN-LAST:event_busquedaLabelMouseEntered

    private void busquedaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busquedaLabelMouseExited
        busquedaLabel.setFont(new java.awt.Font("Segoe UI", 1, 18));
    }//GEN-LAST:event_busquedaLabelMouseExited

    private void registroReservasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroReservasLabelMouseClicked
        Reservas reserva = new Reservas();
        reserva.setLocationRelativeTo(null);
        reserva.setVisible(true);
        dispose();
    }//GEN-LAST:event_registroReservasLabelMouseClicked

    private void busquedaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busquedaLabelMouseClicked
        Busqueda busqueda = new Busqueda();
        busqueda.setLocationRelativeTo(null);
        busqueda.setVisible(true);
        dispose();
    }//GEN-LAST:event_busquedaLabelMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busquedaLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel registroReservasLabel;
    private javax.swing.JLabel reservasLabel;
    private javax.swing.JPanel sistemaPanel;
    private javax.swing.JLabel texto1Label;
    private javax.swing.JLabel texto2Label;
    private javax.swing.JLabel texto3Label;
    private javax.swing.JLabel texto4Label;
    private javax.swing.JLabel texto5Label;
    private javax.swing.JLabel texto6Label;
    // End of variables declaration//GEN-END:variables

//Añadir fecha actual a fechaLabel    

}


