/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.hotelalura.Entidades.Huesped;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import persistencia.HuespedDAO;

/**
 *
 * @author Elián
 */
public class RegistroHuesped extends javax.swing.JFrame {

    int xMouse, yMouse;
    String id;
    HuespedDAO dao;

    /**
     * Creates new form RegistroHuesped
     */
    public RegistroHuesped(Long idReserva) {
        this.id = String.valueOf(idReserva);
        this.dao = new HuespedDAO();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContent = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        atrasLabel = new javax.swing.JLabel();
        imagenLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        apellidoLabel = new javax.swing.JLabel();
        apellidoField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        fechaLabel = new javax.swing.JLabel();
        nacionalidadLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        telefonoField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        reservaLabel = new javax.swing.JLabel();
        reservaField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        fechaChooser = new com.toedter.calendar.JDateChooser();
        paisBox = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        guardarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 910, 634));

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(12, 138, 199));
        panelFondo.setToolTipText("");
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atrasLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        atrasLabel.setForeground(new java.awt.Color(255, 255, 255));
        atrasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atrasLabel.setText("<");
        atrasLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atrasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasLabelMouseClicked(evt);
            }
        });
        panelFondo.add(atrasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 32, -1));

        imagenLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elián\\Documents\\NetBeansProjects\\HotelAlura\\src\\main\\java\\views\\imagenes\\registro.png")); // NOI18N
        panelFondo.add(imagenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        logoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elián\\Documents\\NetBeansProjects\\HotelAlura\\src\\main\\java\\views\\imagenes\\Ha-100px.png")); // NOI18N
        panelFondo.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        panelContent.add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 630));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitLabel.setBackground(new java.awt.Color(255, 255, 255));
        exitLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.setOpaque(true);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(885, Short.MAX_VALUE)
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        panelContent.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(12, 138, 199));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("REGISTRO HUÉSPED");
        panelContent.add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nombreLabel.setForeground(java.awt.SystemColor.textInactiveText);
        nombreLabel.setText("NOMBRE");
        panelContent.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        nombreField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreField.setToolTipText("");
        nombreField.setBorder(null);
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });
        panelContent.add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 230, 30));

        jSeparator1.setForeground(java.awt.SystemColor.textHighlight);
        panelContent.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 230, 10));

        apellidoLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        apellidoLabel.setForeground(new java.awt.Color(102, 102, 102));
        apellidoLabel.setText("APELLIDO");
        panelContent.add(apellidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        apellidoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apellidoField.setToolTipText("");
        apellidoField.setBorder(null);
        apellidoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoFieldActionPerformed(evt);
            }
        });
        panelContent.add(apellidoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 230, 30));

        jSeparator2.setForeground(java.awt.SystemColor.textHighlight);
        panelContent.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 230, 10));

        fechaLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(102, 102, 102));
        fechaLabel.setText("FECHA DE NACIMIENTO");
        panelContent.add(fechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        nacionalidadLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nacionalidadLabel.setForeground(new java.awt.Color(102, 102, 102));
        nacionalidadLabel.setText("NACIONALIDAD");
        panelContent.add(nacionalidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 302, -1, 20));

        telefonoLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        telefonoLabel.setForeground(new java.awt.Color(102, 102, 102));
        telefonoLabel.setText("TELEFONO");
        panelContent.add(telefonoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        telefonoField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefonoField.setToolTipText("");
        telefonoField.setBorder(null);
        telefonoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoFieldActionPerformed(evt);
            }
        });
        panelContent.add(telefonoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 230, 30));

        jSeparator5.setForeground(java.awt.SystemColor.textHighlight);
        panelContent.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 230, 10));

        reservaLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        reservaLabel.setForeground(new java.awt.Color(102, 102, 102));
        reservaLabel.setText("NÚMERO DE RESERVA");
        panelContent.add(reservaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, -1));

        reservaField.setEditable(false);
        reservaField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reservaField.setText(id);
        reservaField.setToolTipText("");
        reservaField.setBorder(null);
        reservaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaFieldActionPerformed(evt);
            }
        });
        panelContent.add(reservaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 230, 30));

        jSeparator6.setForeground(java.awt.SystemColor.textHighlight);
        jSeparator6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panelContent.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 230, 10));

        fechaChooser.setDateFormatString("dd/MM/yyyy");
        fechaChooser.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elián\\Documents\\NetBeansProjects\\HotelAlura\\src\\main\\java\\views\\imagenes\\icon-reservas.png"));
        fechaChooser.setMaxSelectableDate(new Date());
        fechaChooser.setMinSelectableDate(new java.util.Date(-2208969728000L));
        panelContent.add(fechaChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 230, 40));

        paisBox.setModel(new DefaultComboBoxModel(new String[] {"afgano-afgana", "alemán-", "alemana", "árabe-árabe", "argentino-argentina", "australiano-australiana", "belga-belga", "boliviano-boliviana", "brasileño-brasileña", "camboyano-camboyana", "canadiense-canadiense", "chileno-chilena", "chino-china", "colombiano-colombiana", "coreano-coreana", "costarricense-costarricense", "cubano-cubana", "danés-danesa", "ecuatoriano-ecuatoriana", "egipcio-egipcia", "salvadoreño-salvadoreña", "escocés-escocesa", "español-española", "estadounidense-estadounidense", "estonio-estonia", "etiope-etiope", "filipino-filipina", "finlandés-finlandesa", "francés-francesa", "galés-galesa", "griego-griega", "guatemalteco-guatemalteca", "haitiano-haitiana", "holandés-holandesa", "hondureño-hondureña", "indonés-indonesa", "inglés-inglesa", "iraquí-iraquí", "iraní-iraní", "irlandés-irlandesa", "israelí-israelí", "italiano-italiana", "japonés-japonesa", "jordano-jordana", "laosiano-laosiana", "letón-letona", "letonés-letonesa", "malayo-malaya", "marroquí-marroquí", "mexicano-mexicana", "nicaragüense-nicaragüense", "noruego-noruega", "neozelandés-neozelandesa", "panameño-panameña", "paraguayo-paraguaya", "peruano-peruana", "polaco-polaca", "portugués-portuguesa", "puertorriqueño-puertorriqueño", "dominicano-dominicana", "rumano-rumana", "ruso-rusa", "sueco-sueca", "suizo-suiza", "tailandés-tailandesa", "taiwanes-taiwanesa", "turco-turca", "ucraniano-ucraniana", "uruguayo-uruguaya", "venezolano-venezolana", "vietnamita-vietnamita"}));
        paisBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisBoxActionPerformed(evt);
            }
        });
        panelContent.add(paisBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 230, 40));

        jSeparator7.setForeground(java.awt.SystemColor.textHighlight);
        panelContent.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 230, 10));

        jSeparator8.setForeground(java.awt.SystemColor.textHighlight);
        panelContent.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 230, 10));

        guardarBtn.setBackground(new java.awt.Color(12, 138, 199));
        guardarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        guardarBtn.setForeground(new java.awt.Color(255, 255, 255));
        guardarBtn.setText("GUARDAR");
        guardarBtn.setBorder(null);
        guardarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarBtnMouseClicked(evt);
            }
        });
        panelContent.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 560, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void atrasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasLabelMouseClicked
        Reservas reservas = new Reservas();
        reservas.setLocationRelativeTo(null);
        reservas.setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasLabelMouseClicked

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void apellidoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoFieldActionPerformed

    private void telefonoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoFieldActionPerformed

    private void reservaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservaFieldActionPerformed

    private void paisBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisBoxActionPerformed

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        exitLabel.setBackground(Color.red);
        exitLabel.setForeground(Color.white);
    }//GEN-LAST:event_exitLabelMouseEntered

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitLabel.setBackground(Color.white);
        exitLabel.setForeground(Color.black);
    }//GEN-LAST:event_exitLabelMouseExited

    private void guardarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarBtnMouseClicked
        if (!nombreField.equals("") && fechaChooser.getDate() != null && !apellidoField.equals("") && !telefonoField.equals("")) {
            String fechaN = ((JTextField) fechaChooser.getDateEditor().getUiComponent()).getText();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            try {
                Date fechaNac = formato.parse(fechaN);
                Date fechaNacSQL = new Date(fechaNac.getTime());
                int nreserva = Integer.parseInt(reservaField.getText());
                Huesped huespedes = new Huesped(nombreField.getText(), apellidoField.getText(), fechaNacSQL, paisBox.getSelectedItem().toString(), Long.parseLong(telefonoField.getText()), nreserva);
                this.dao.persistirEntidad(huespedes);
                JOptionPane.showMessageDialog(null, "Huesped guardado con éxito!");
                MenuUsuario menu = new MenuUsuario();
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
                dispose();
            } catch (ParseException e) {
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes llenar todos los campos.");
        }
    }//GEN-LAST:event_guardarBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroHuesped(0l).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoField;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JLabel atrasLabel;
    private javax.swing.JLabel exitLabel;
    private com.toedter.calendar.JDateChooser fechaChooser;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JPanel header;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel nacionalidadLabel;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JComboBox<String> paisBox;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTextField reservaField;
    private javax.swing.JLabel reservaLabel;
    private javax.swing.JTextField telefonoField;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
